version: '3.8'
services:
    habitat-1:
        working_dir: /habitat
        volumes:
            - ./data/procs/web:/habitat/web
            - ./data/procs/bin:/habitat/procs/bin
            - ./bin:/habitat/bin
        command:
          - ./habitat/bin/amd64-linux/habitat --hostname localhost
          - ./habitat/procs/bin/amd64-linux/community-backend
          - serve -s /habitat/web/community
        environment:
            - HABITAT_PATH=/habitat
        image: ubuntu:latest
        build: .
        ports:
            - 8009:8008
            - 6001:6000
            - 3001:3000
            - 2040:2000
