version: '3.8'
services:
    habitat-1:
        image: ubuntu:latest
        working_dir: /habitat
        volumes:
            - .habitat/procs:/habitat/procs
            - .habitat/apps:/habitat/apps
            - ./cmd/bin/amd64-linux:/habitat/bin
        command: /habitat/bin/habitat --hostname localhost
        environment:
            - HABITAT_APP_PATH=/habitat/apps
            - HABITAT_PATH=/habitat
        build: .
        ports:
            - 2000:2040
            - 3000:2041
            - 8760:8765
    habitat-2:
        image: ubuntu:latest
        working_dir: /habitat
        volumes:
            - .habitat/procs:/habitat/procs
            - .habitat/apps:/habitat/apps
            - ./cmd/bin/amd64-linux:/habitat/bin
        command: /habitat/bin/habitat --hostname localhost
        environment:
            - HABITAT_APP_PATH=/habitat/apps
            - HABITAT_PATH=/habitat
        build: .
        ports:
            - 2001:2040
            - 3001:2041
            - 8761:8765
