version: '3.8'
services:
    alice:
        working_dir: /habitat
        volumes:
            - .habitat/procs:/habitat/procs
            - .habitat/apps:/habitat/apps
            - ./dist/bin:/habitat/bin
        command: /habitat/bin/amd64-linux/habitat --hostname localhost
        environment:
            - HABITAT_PATH=/habitat
            - HABITAT_APP_PATH=/habitat/apps
        image: habitat:latest
        ports:
            - 2000:2040
            - 3000:2041
    bob:
        working_dir: /habitat
        volumes:
            - .habitat/procs:/habitat/procs
            - .habitat/apps:/habitat/apps
            - ./dist/bin:/habitat/bin
        command: /habitat/bin/amd64-linux/habitat --hostname localhost
        environment:
            - HABITAT_PATH=/habitat
            - HABITAT_APP_PATH=/habitat/apps
        image: habitat:latest
        ports:
            - 2001:2040
            - 3001:2041
    charlie:
        working_dir: /habitat
        volumes:
            - .habitat/procs:/habitat/procs
            - .habitat/apps:/habitat/apps
            - ./dist/bin:/habitat/bin
        command: /habitat/bin/amd64-linux/habitat --hostname localhost
        environment:
            - HABITAT_PATH=/habitat
            - HABITAT_APP_PATH=/habitat/apps
        image: habitat:latest
        ports:
            - 2002:2040
            - 3002:2041
       
