#!/bin/bash

. "$(dirname "$0")/tools/lib.bash"

log::info "Installing packages..."

# Install IPFS
RUNDIR=$(mktemp -d)
cd $RUNDIR
wget https://dist.ipfs.io/kubo/v0.14.0/kubo_v0.14.0_linux-amd64.tar.gz
tar -xvzf kubo_v0.14.0_linux-amd64.tar.gz
cd kubo
sudo bash install.sh
cd "$(dirname "$0")"
rm -rf $RUNDIR
