#!/bin/bash

if [ ! -d "$IPFS_PATH" ]; then
    mkdir -p $IPFS_PATH
    echo "WARNING: this is not the standard way to initialize a private ipfs network"
    echo "WARNING: use this for testing purposes only"
    a="initializing IPFS in "
    echo $a$IPFS_PATH
    IPFS_PATH=$IPFS_PATH ipfs init
else 
    echo "ipfs already initialized"
fi

sleep 2
IPFS_PATH=$IPFS_PATH ipfs daemon
