#!/usr/bin/env bash

# t is for TCP port, g is for Gateway port, s is for Swarm port
# TODO later (not obvious how to change the ports programmatically on start up)
while getopts t:g:s flag
do
    case "${flag}" in
        t) tcp=${OPTARG};;
        g) gate=${OPTARG};;
        s) swarm=${OPTARG};;
    esac
done

export INPUT_PATH=$1

if [ ! -d $INPUT_PATH ]; then
    mkdir -p $INPUT_PATH
    echo "initializing IPFS at $INPUT_PATH"
    IPFS_PATH=$INPUT_PATH ipfs init
    IPFS_PATH=$INPUT_PATH ipfs bootstrap rm --all
    IPFS_PATH=$INPUT_PATH ipfs config profile apply randomports
else 
    echo "ipfs already initialized at $INPUT_PATH, showing config"
fi
