name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install Packages
      run: ./install-packages

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Lint
      run: |
        export PATH=$PATH:${HOME}/bin
        make lint

    - name: Build
      run: make && make install

    - name: Docker Build
      run: docker build .

    - name: Test
      run: make test

